# ############################################################################
# Model: SSL: Best-RQ HyperConformer
# Encoder: HyperConformer Encoder (w/Random Projection Quantizer)
# loss: Cross entropy
# Training: Librispeech 960h
# Authors:  Ryan Whetten
# ############################################################################
# Seed needs to be set at top of yaml, before objects with parameters are made

seed: 1000
__set_seed: !apply:torch.manual_seed [!ref <seed>]

project_name: alt-attention
experiment_name: ff_lg
architecture: brq-fastformer
wandb_offline: True

data_folder: /gpfsdswork/dataset/LibriSpeechAsrCorpus
output_folder: !ref results/ff_lg/<seed>
output_wer_folder: !ref <output_folder>/
sim_test_time: 10
sim_batch_size: 10

ckpt_interval_min: 15
save_folder: !ref <output_folder>/save
# Logging file for every N optimizer steps (many lines)
train_steps_log: !ref <output_folder>/train_steps_log.txt
# Logging file per epoch
train_stage_log: !ref <output_folder>/train_stage_log.txt

train_splits: ["train-clean-100", "train-clean-360", "train-other-500"]
dev_splits: ["dev-clean"]
test_splits: ["test-clean"]
train_csv: !ref <output_folder>/train.csv
valid_csv: !ref <output_folder>/dev-clean.csv
skip_prep: False

avoid_if_longer_than: 60.0
avoid_if_shorter_than: 2.0
log_interval: 500 # Logging every N optimizer steps
precision: bf16
max_grad_norm: 10.

# Training parameters
# To make Transformers converge, the global bath size should be large enough.
# The global batch size is computed as batch_size * n_gpus * gradient_accumulation.
# Empirically, we found that this value should be >= 128.
# Please, set your parameters accordingly.

number_of_epochs: 1000
optimizer_step_limit: 205000


seconds_per_batch: 400 
train_num_buckets: 150
grad_accumulation_factor: 2

train_dataloader_options:
   num_workers: 2

test_dataloader_options:
   batch_size:  8 # DynamicBatching not used at testing time
   num_workers: 2

# Training parameters (based on Section 4.1.1 of Best-RQ paper)
lr: 0.0008
lr_init: 0.0
weight_decay: 0.01
warmup: 25000

# Feature parameters
sample_rate: 16000
n_fft: 400
n_mels: 80
hop_length: 10
pad_to_divisible_by: 4

####################### Model parameters ###########################
# Transformer
d_model: 920
nhead: 8 # table 1 https://arxiv.org/pdf/2010.10504.pdf
num_encoder_layers: 24 # section 4.1.1
num_decoder_layers: 0
d_ffn: 2048
transformer_dropout: 0.1
activation: !name:torch.nn.GELU
output_neurons: 5000
encoder_layerdrop: 0.1
# specify 'hypermixing' for usage of multi-head HyperMixer instead of MultiHeadAttention
# You can also specify RelPosMHAXL for conformer
# attention_type: hypermixing
attention_type: fastattention

# option 1) 'conformer' for HyperConformer; 
# option 2) 'transformer' for vanilla HyperMixer
# option 3) 'branchformer': HyperBranchformer
encoder_module: conformer

# 15% masking
mask_length: 4 # for 400ms
mask_prob: 0.15
noise_mean: 0
noise_std: 0.1

# quantizer parameter
p_input: 320
cb_dim: 16
cb_vocab: 8192


############################## models ################################

CNN: !new:speechbrain.lobes.models.convolution.ConvolutionFrontEnd
    input_shape: (8, 10, 80)
    num_blocks: 2
    num_layers_per_block: 1
    out_channels: (128, 32)
    kernel_sizes: (3, 3)
    strides: (2, 2)
    residuals: (False, False)

Transformer: !new:speechbrain.lobes.models.transformer.TransformerASR.TransformerASR # yamllint disable-line rule:line-length
    input_size: 640
    tgt_vocab: !ref <output_neurons>
    d_model: !ref <d_model>
    nhead: !ref <nhead>
    num_encoder_layers: !ref <num_encoder_layers>
    num_decoder_layers: !ref <num_decoder_layers>
    d_ffn: !ref <d_ffn>
    dropout: !ref <transformer_dropout>
    activation: !ref <activation>
    encoder_module: !ref <encoder_module>
    attention_type: !ref <attention_type>
    normalize_before: True
    causal: False
    layerdrop_prob: !ref <encoder_layerdrop>

# We must call an encoder wrapper so the decoder isn't run (we don't have any)
wrapper: !new:speechbrain.lobes.models.transformer.TransformerASR.EncoderWrapper
   transformer: !ref <Transformer>

Quantizer: !new:.quantiser.RandomProjectionQuantizer
    # projection
    input_dim: !ref <p_input>
    # codebook
    cb_dim: !ref <cb_dim>    
    cb_vocab: !ref <cb_vocab>

linear: !new:speechbrain.nnet.linear.Linear
    input_size: !ref <d_model>
    n_neurons: !ref <cb_vocab>

modules:
    CNN: !ref <CNN>
    wrapper: !ref <wrapper>
    Quantizer: !ref <Quantizer>
    normalize: !ref <normalize>
    linear: !ref <linear>

model: !new:torch.nn.ModuleList
    - [!ref <CNN>, !ref <wrapper>, !ref <Quantizer>, !ref <linear>]

############################## features ################################


compute_features: !new:speechbrain.lobes.features.Fbank
    sample_rate: !ref <sample_rate>
    n_fft: !ref <n_fft>
    n_mels: !ref <n_mels>

normalize: !new:speechbrain.processing.features.InputNormalization
    norm_type: global
    update_until_epoch: 4

############################## running ################################

optimizer: !name:torch.optim.AdamW
    lr: !ref <lr>
    betas: (0.9, 0.98)
    weight_decay: !ref <weight_decay>

noam_annealing: !new:speechbrain.nnet.schedulers.NoamScheduler
    lr_initial: !ref <lr>
    n_warmup_steps: 25000

epoch_counter: !new:speechbrain.utils.epoch_loop.EpochCounter
    limit: !ref <number_of_epochs>

train_steps_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
   save_file: !ref <train_steps_log>

train_stage_logger: !new:speechbrain.utils.train_logger.FileTrainLogger
   save_file: !ref <train_stage_log>

checkpointer: !new:speechbrain.utils.checkpoints.Checkpointer
    checkpoints_dir: !ref <save_folder>
    recoverables:
        model: !ref <model>
        noam_scheduler: !ref <noam_annealing>
        normalizer: !ref <normalize>
        counter: !ref <epoch_counter>
